# .github/workflows/prototype-ci.yml
name: Prototype CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r cli/requirements.txt
    
    - name: Test Lambda functions
      run: |
        python -m pytest tests/test_lambda.py -v
    
    - name: Test CLI interface
      run: |
        python -m pytest tests/test_cli.py -v

  deploy-infrastructure:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy with Terraform
      run: |
        cd terraform
        terraform init
        terraform plan
        terraform apply -auto-approve
    
    - name: Package and deploy Lambda
      run: |
        cd backend/lambdas
        zip -r chat_handler.zip .
        aws lambda update-function-code \
          --function-name chatbot-chat-handler \
          --zip-file fileb://chat_handler.zip

  test-integration:
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Test CLI integration
      run: |
        python cli/chatbot_cli.py --test-mode
        echo "✅ CLI integration test passed"