name: ChatBot Prototype CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  PROJECT_NAME: chatbot-saas

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r cli/requirements.txt
        pip install -r backend/lambdas/requirements.txt
    
    - name: Run unit tests
      run: |
        python -m pytest tests/ -v --tb=short
    
    - name: Lint Python code
      run: |
        pip install flake8
        flake8 backend/lambdas/ cli/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics

  validate-terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
    
    - name: Terraform Format Check
      run: |
        cd terraform
        terraform fmt -check
    
    - name: Terraform Init
      run: |
        cd terraform
        terraform init -backend=false
    
    - name: Terraform Validate
      run: |
        cd terraform
        terraform validate

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: [test, validate-terraform]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
        terraform_wrapper: false
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Package Lambda function
      run: |
        cd backend/lambdas
        zip -r ../../terraform/chat_handler.zip . -x "*.pyc" "*__pycache__*"
    
    - name: Deploy infrastructure
      run: |
        cd terraform
        terraform init
        terraform plan -out=tfplan
        terraform apply -auto-approve tfplan
    
    - name: Get deployment outputs
      id: terraform-output
      run: |
        cd terraform
        echo "api_gateway_url=$(terraform output -raw api_gateway_url)" >> $GITHUB_OUTPUT
        echo "lambda_function_name=$(terraform output -raw lambda_function_name)" >> $GITHUB_OUTPUT
        echo "sagemaker_endpoint_name=$(terraform output -raw sagemaker_endpoint_name)" >> $GITHUB_OUTPUT
    
    - name: Wait for SageMaker endpoint
      run: |
        ENDPOINT_NAME="${{ steps.terraform-output.outputs.sagemaker_endpoint_name }}"
        echo "Waiting for SageMaker endpoint: $ENDPOINT_NAME"
        
        max_attempts=30
        attempt=1
        
        while [ $attempt -le $max_attempts ]; do
          STATUS=$(aws sagemaker describe-endpoint --endpoint-name $ENDPOINT_NAME --query 'EndpointStatus' --output text)
          echo "Attempt $attempt/$max_attempts - Endpoint status: $STATUS"
          
          if [ "$STATUS" = "InService" ]; then
            echo "✅ SageMaker endpoint is ready!"
            break
          elif [ "$STATUS" = "Failed" ]; then
            echo "❌ SageMaker endpoint deployment failed"
            exit 1
          fi
          
          sleep 60
          attempt=$((attempt + 1))
        done
        
        if [ $attempt -gt $max_attempts ]; then
          echo "❌ Timeout waiting for SageMaker endpoint"
          exit 1
        fi
    
    - name: Test deployment
      run: |
        pip install requests
        
        # Test API Gateway health
        API_URL="${{ steps.terraform-output.outputs.api_gateway_url }}"
        echo "Testing API at: $API_URL"
        
        # Simple health check
        python3 -c "
import requests
import json
import sys

api_url = '$API_URL/chat'
payload = {'message': 'Hello, this is a CI/CD test', 'session_id': 'ci-test-123'}

try:
    response = requests.post(api_url, json=payload, timeout=30)
    print(f'Status Code: {response.status_code}')
    print(f'Response: {response.text}')
    
    if response.status_code == 200:
        print('✅ API test passed!')
    else:
        print('❌ API test failed!')
        sys.exit(1)
except Exception as e:
    print(f'❌ API test error: {e}')
    sys.exit(1)
        "
    
    - name: Deployment summary
      run: |
        echo "🎉 Deployment completed successfully!"
        echo "📊 Deployment Information:"
        echo "   API Gateway URL: ${{ steps.terraform-output.outputs.api_gateway_url }}"
        echo "   Lambda Function: ${{ steps.terraform-output.outputs.lambda_function_name }}"
        echo "   SageMaker Endpoint: ${{ steps.terraform-output.outputs.sagemaker_endpoint_name }}"
        echo ""
        echo "🔗 Test the CLI:"
        echo "   git clone <repo> && cd chatbot-saas-prototype"
        echo "   export API_GATEWAY_URL=${{ steps.terraform-output.outputs.api_gateway_url }}"
        echo "   cd cli && python3 chatbot_cli.py"

  cleanup-on-failure:
    name: Cleanup on Failure
    runs-on: ubuntu-latest
    needs: [deploy]
    if: failure() && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
    
    - name: Cleanup failed deployment
      run: |
        cd terraform
        terraform init
        terraform destroy -auto-approve
        echo "🧹 Cleaned up failed deployment"